### ISSUE TITLE
Request to remove colorize or make it optional

### ISSUE THREAD

**Issue by mandos21** [ylecuyer/puma-status#17]
Colorize is released under GPL, which limits the use of puma-status.

**Comment by ylecuyer** [comment]
Could you elaborate on the "which limits the use of puma-status" and maybe give an example?

Otherwise, the color stuff is handled in https://github.com/ylecuyer/puma-status/blob/master/lib/helpers.rb#L15, a PR is welcome if you want to replace the gem with a non GPL equivalent or recode the colorize part (which only handles 3 colors)

**Comment by mandos21** [comment]
GPL applications can't be used in for-sale software development because they require the entire source code be released.

**Comment by jarthod** [comment]
@mandos21 I may be wrong but that is if you integrate and/or modify the source code, you can still use GPL code as a tool. The linux kernel is GPL and you can use it to run your server for a commercial application. What you can't do is take colorize and/or puma-status code and modify it close source or resell it.

**Comment by ylecuyer** [comment]
Closing as we have no more argument against having colorize dependency, and for those who don't want color they can use the `NO_COLOR` env variable: https://no-color.org/
