### ISSUE TITLE
Methods added at root level

### ISSUE THREAD

**Issue by esposito** [ylecuyer/puma-status#32]
When I add this gem to my gemfile, a number of methods are introduced at the root level. In version 1.5 of this gem, this caused to overwrite the Kernel `warn` method. 

Is there a reason this gem is set up this way? Would it be possible to put all methods in one or more Ruby classes?

**Comment by ylecuyer** [comment]
Hello

> Is there a reason this gem is set up this way?

This gem hasn't been architectured to be included in a gemfile but to be installed with `gem install puma-status` instead.
If you really want to add it to your gemfile, you probably need to add `require: false` so that the code isn't loaded into your project or move it to a group which isn't loaded by default.

> Would it be possible to put all methods in one or more Ruby classes?

I would accept a PR doing this

Regards
